
package contrato;

import java.awt.event.ActionEvent;
import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;


/**
 *
 * @author JB
 */
public class contra extends javax.swing.JPanel {

    
    Contrato sellos;
    String Item = "";
   
 //esto es lo nuevo  ##########################################################################
	
	
  private long horasDormirSegundos; // Número de segundos que el usuario planea dormir
   private long tiempoInicioSueno=0; // Tiempo en milisegundos en el que se inicia el sueño

    	
    private Timer timer; // Timer para el cronómetro
    private int horasDormir; // Número de horas que el usuario planea dormir
    private int horasTranscurridas; // Número de horas transcurridas
		
/////######################################################################################### 
    
    public contra() {
        
        initComponents();
        boxUno.addItem("Nutricion");
        boxUno.addItem("Sueno");
        boxUno.addItem("Productividad");
        boxUno.addItem("Felicidad");
        boxUno.addItem("Salud");
        boxUno.addItem("Finanzas");
        
        sellos = new Contrato();
//######################################################################################################
    // Inicializar el timer con un ActionListener para contar las horas
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Incrementar el contador de horas transcurridas
                horasTranscurridas++;

                // Actualizar la interfaz de usuario para mostrar las horas transcurridas
                // Aquí debes tener un JLabel o JTextArea donde mostrar el tiempo transcurrido
                // Supongamos que tienes un JLabel llamado labelTiempo
                labelTiempo.setText("Horas transcurridas: " + horasTranscurridas);

                // Verificar si se han alcanzado las horas de sueño planeadas
                if (horasTranscurridas >= horasDormir) {
                    // Detener el timer
                    timer.stop();

                    // Reproducir un sonido para notificar que se alcanzaron las horas de sueño
                    // Puedes usar la clase javax.sound.sampled para reproducir un sonido

                    // Mostrar un mensaje al usuario
                    JOptionPane.showMessageDialog(null, "Has alcanzado tus horas de sueño planificadas");
                }
            }
		 });
        
//#################################################################################################################         

    }

// Aqui dejare la variable global de "ITEM"

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        boxUno = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        jMenu4.setText("File");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar1.add(jMenu5);

        jMenuItem2.setText("jMenuItem2");

        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setText("Objetivos:");

        jLabel3.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel3.setText("Usuario");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        boxUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "_", "Nutricion", "Sueno", "Productividad", "Felicidad", "Salud", "Finanzas" }));
        boxUno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxUnoItemStateChanged(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Registro");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxUno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton2)
                        .addGap(84, 84, 84)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(boxUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(146, 146, 146))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Se configuro el menu de las opciones desplegables al que llamamos "BoxUno"

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

   //asigna los datos y los configura 
    private void boxUnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxUnoItemStateChanged
        // Verificar si se seleccionó un elemento
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Obtener el ítem seleccionado
            String itemSeleccionado = (String) boxUno.getSelectedItem();
            // Realizar acciones según el ítem seleccionado
            switch(itemSeleccionado) {
                case "Nutricion":
                // Acciones para Nutricion
                JOptionPane.showMessageDialog(null, "Seleccionaste Nutricion");
                break;
//########################################################################################################       
                case "Sueno":
                     JOptionPane.showMessageDialog(null, "Seleccionaste Sueno");

                    // Solicitar al usuario la cantidad de horas de sueño
                    String horasSueno = JOptionPane.showInputDialog(null, "Por favor ingresa la cantidad de horas que planeas dormir:");

                    // Validar si se ingresó un valor
                    if (horasSueno != null && !horasSueno.isEmpty()) {
                        // Convertir el valor ingresado a entero
                        horasDormir = Integer.parseInt(horasSueno);

                        // Inicializar el contador de horas transcurridas
                        horasTranscurridas = 0;

                        // Iniciar el timer
                        timer.start();
                    } else {
                        // El usuario canceló o no ingresó un valor, manejar según sea necesario
                        JOptionPane.showMessageDialog(null, "No ingresaste la cantidad de horas de sueño.");
                    }
                    break;
                   
//########################################################################################################		
                
               
                
                /*
                case "Sueno":
                // Acciones para Sueno
                JOptionPane.showMessageDialog(null, "Seleccionaste Sueno");
                // Solicitar al usuario la cantidad de horas de sueño
                String horasSueno = JOptionPane.showInputDialog(null, "Por favor ingresa la cantidad de horas que planeas dormir:");

                // Validar si se ingresó un valor
                if (horasSueno != null && !horasSueno.isEmpty()) {
                    // Realizar acciones con la cantidad de horas de sueño
                    JOptionPane.showMessageDialog(null, "Seleccionaste Sueno y planeas dormir " + horasSueno + " horas.");
                } else {
                    // El usuario canceló o no ingresó un valor, manejar según sea necesario
                    JOptionPane.showMessageDialog(null, "No ingresaste la cantidad de horas de sueño.");
                }
                break;
                */
                case "Productividad":
                // Acciones para Productividad
                JOptionPane.showMessageDialog(null, "Seleccionaste Productividad");
                break;
                case "Felicidad":
                // Acciones para Felicidad
                JOptionPane.showMessageDialog(null, "Seleccionaste Felicidad");
                break;
                case "Salud":
                // Acciones para Salud
                JOptionPane.showMessageDialog(null, "Seleccionaste Salud");
                break;
                case "Finanzas":
                // Acciones para Finanzas
                JOptionPane.showMessageDialog(null, "Seleccionaste Finanzas");
                break;
                 default:
                break;
            }
        }
    }//GEN-LAST:event_boxUnoItemStateChanged
//SALIR
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    
  
  
   
    public static void main(String[] args) {
        JFrame frame = new JFrame("Mi Aplicación");

        // Crear una instancia del panel contra
        contra panel = new contra();
        
        frame.add(panel);

        // Configurar el comportamiento al cerrar la ventana
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Ajustar el tamaño del marco automáticamente según el contenido
        frame.pack();

        // Hacer visible el marco
        frame.setVisible(true);

// Crear y configurar el marco principal
        contra principal = new contra();
        
        principal.setVisible(true);

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxUno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelTiempo;
    // End of variables declaration//GEN-END:variables



}