/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.UsuarioController;
import javax.swing.JOptionPane;
import modelo.Usuario;

public class ConsultarContratos extends javax.swing.JFrame {

    UsuarioController userController = new UsuarioController();

    /**
     * Creates new form ConsultarContratos
     */
    public ConsultarContratos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        contratosComboBox = new javax.swing.JComboBox<>();
        consultaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatusContrato = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Contratos");
        setResizable(false);

        jLabel2.setText("Usuario: ");

        jLabel1.setText("Haz cumplido con tu contrato de: ");

        contratosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Felicidad", "Finanzas", "Nutrición", "Productividad", "Salud", "Sueño" }));

        consultaBtn.setText("Consultar");
        consultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setEnabled(false);

        StatusContrato.setColumns(20);
        StatusContrato.setFont(new java.awt.Font("Monospaced", 3, 13)); // NOI18N
        StatusContrato.setRows(5);
        StatusContrato.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        StatusContrato.setEnabled(false);
        jScrollPane1.setViewportView(StatusContrato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contratosComboBox, 0, 206, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Username))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(consultaBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(contratosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBtnActionPerformed
        Usuario usuarioExistente = UsuarioController.buscarUsuario(this.Username.getText());
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(null, "¡Error! No existe un usuario con el nombre " + this.Username.getText() + ".", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String selectedContrato = (String) this.contratosComboBox.getSelectedItem();
            switch (selectedContrato) {
                case "Felicidad":
                    ConsultaContratos(usuarioExistente.getNombre(),selectedContrato);
                    break;
                case "Finanzas":
                    ConsultaContratos(usuarioExistente.getNombre(),selectedContrato);
                    break;
                case "Nutrición":
                    ConsultaContratos(usuarioExistente.getNombre(),selectedContrato);
                    break;
                case "Productividad":
                    ConsultaContratos(usuarioExistente.getNombre(),selectedContrato);
                    break;
                case "Salud":
                    ConsultaContratos(usuarioExistente.getNombre(),selectedContrato);
                    break;
                case "Sueño":
                    ConsultaContratos(usuarioExistente.getNombre(),selectedContrato);
                    break;
                default:
                    this.StatusContrato.setText("Instrucción no válida.");
                    break;
            }

        }
    }//GEN-LAST:event_consultaBtnActionPerformed

    private void ConsultaContratos(String userName, String contrato){
        boolean contratoValido = UsuarioController.consultarEstadoContrato(userName, contrato);
        if(contratoValido){
            this.StatusContrato.setText("¡Felicidades por tu esfuerzo!");
        }else{
            this.StatusContrato.setText("¡Ánimos!, no te rindas aún.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarContratos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea StatusContrato;
    private javax.swing.JTextField Username;
    private javax.swing.JButton consultaBtn;
    private javax.swing.JComboBox<String> contratosComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
