package vista;
import controlador.UsuarioController;
import javax.swing.JOptionPane;
import modelo.Usuario;
public class MenuPrincipal extends javax.swing.JFrame {
    UsuarioController userController = new UsuarioController();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        regUsuariosMenu = new javax.swing.JMenuItem();
        ElUsuariosMenu = new javax.swing.JMenuItem();
        VerUsuariosMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        FelicidadMenu = new javax.swing.JMenu();
        ListarChecksFelicidadItem = new javax.swing.JMenuItem();
        consultarEstadoFelicidadItem = new javax.swing.JMenuItem();
        FinanzasMenu = new javax.swing.JMenu();
        NutricionMenu = new javax.swing.JMenu();
        ProductividadMenu = new javax.swing.JMenu();
        SaludMenu = new javax.swing.JMenu();
        SueñoMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");
        setName("menuPrincipal"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jMenu1.setText("Usuarios");

        regUsuariosMenu.setText("Registrar usuarios");
        regUsuariosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUsuariosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(regUsuariosMenu);

        ElUsuariosMenu.setText("Eliminar usuarios");
        ElUsuariosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElUsuariosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ElUsuariosMenu);

        VerUsuariosMenu.setText("Ver usuarios");
        VerUsuariosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerUsuariosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(VerUsuariosMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Contratos");

        FelicidadMenu.setText("Felicidad");

        ListarChecksFelicidadItem.setText("Listar Checks");
        FelicidadMenu.add(ListarChecksFelicidadItem);

        consultarEstadoFelicidadItem.setText("Consultar estado");
        FelicidadMenu.add(consultarEstadoFelicidadItem);

        jMenu2.add(FelicidadMenu);

        FinanzasMenu.setText("Finanzas");
        jMenu2.add(FinanzasMenu);

        NutricionMenu.setText("Nutrición");
        jMenu2.add(NutricionMenu);

        ProductividadMenu.setText("Productividad");
        jMenu2.add(ProductividadMenu);

        SaludMenu.setText("Salud");
        jMenu2.add(SaludMenu);

        SueñoMenu.setText("Sueño");
        jMenu2.add(SueñoMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regUsuariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUsuariosMenuActionPerformed
        String usuario=JOptionPane.showInputDialog("Escriba el nombre del usuario a ingresar:");
        this.userController.agregarUsuario(usuario);
    }//GEN-LAST:event_regUsuariosMenuActionPerformed

    private void ElUsuariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElUsuariosMenuActionPerformed
        String usuario=JOptionPane.showInputDialog("Escriba el nombre del usuario a eliminar:");
        this.userController.eliminarUsuario(usuario);
    }//GEN-LAST:event_ElUsuariosMenuActionPerformed

    private void VerUsuariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerUsuariosMenuActionPerformed
        System.out.println(this.userController.toString());
    }//GEN-LAST:event_VerUsuariosMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ElUsuariosMenu;
    private javax.swing.JMenu FelicidadMenu;
    private javax.swing.JMenu FinanzasMenu;
    private javax.swing.JMenuItem ListarChecksFelicidadItem;
    private javax.swing.JMenu NutricionMenu;
    private javax.swing.JMenu ProductividadMenu;
    private javax.swing.JMenu SaludMenu;
    private javax.swing.JMenu SueñoMenu;
    private javax.swing.JMenuItem VerUsuariosMenu;
    private javax.swing.JMenuItem consultarEstadoFelicidadItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem regUsuariosMenu;
    // End of variables declaration//GEN-END:variables
}
