/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.UsuarioController;
import javax.swing.JOptionPane;
import modelo.Usuario;

public class RegistroContratoProductividad extends javax.swing.JFrame {
    UsuarioController userController = new UsuarioController();

    /**
     * Creates new form RegistroContratoFelicidad
     */
    public RegistroContratoProductividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CancelaSus = new javax.swing.JCheckBox();
        SilenciaNot = new javax.swing.JCheckBox();
        registrar = new javax.swing.JButton();
        Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Silencioso = new javax.swing.JCheckBox();
        FiltrosCorreos = new javax.swing.JCheckBox();
        EliminaJuegos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar felicidad");
        setResizable(false);

        jLabel1.setText("Contrato de Productividad");

        CancelaSus.setText("Cancelas suscripciones promocionales");
        CancelaSus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelaSusActionPerformed(evt);
            }
        });

        SilenciaNot.setText("Silenciar notificaciones y chats grupales");

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        Silencioso.setText("Modo silencioso en el movil");

        FiltrosCorreos.setText("Filtros de correo electrónicos");
        FiltrosCorreos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrosCorreosActionPerformed(evt);
            }
        });

        EliminaJuegos.setText("Eliminar juegos y redes sociales del movil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(registrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminaJuegos)
                            .addComponent(FiltrosCorreos)
                            .addComponent(Silencioso)
                            .addComponent(jLabel1)
                            .addComponent(SilenciaNot)
                            .addComponent(CancelaSus))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelaSus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SilenciaNot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Silencioso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiltrosCorreos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminaJuegos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(registrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelaSusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelaSusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelaSusActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        String username = this.Username.getText();
        Usuario usuarioExistente= UsuarioController.buscarUsuario(username);
        if (usuarioExistente == null) {
            JOptionPane.showMessageDialog(null, "¡Error! No existe un usuario con el nombre " + username + ".", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            usuarioExistente.getContratoProductividad().setCancelaSuscripcionEmail(this.CancelaSus.isSelected());
            usuarioExistente.getContratoProductividad().setApagaNotificaciones(this.SilenciaNot.isSelected());
            usuarioExistente.getContratoProductividad().setModoSilencioCelular(this.Silencioso.isSelected());
            usuarioExistente.getContratoProductividad().setFiltroCorreoElectronico(this.FiltrosCorreos.isSelected());
            usuarioExistente.getContratoProductividad().setEliminaJuegosRedesSociales(this.EliminaJuegos.isSelected());
            JOptionPane.showMessageDialog(null, "Contrato de Productividad del usuario " + username + " fué modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void FiltrosCorreosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrosCorreosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltrosCorreosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroContratoProductividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroContratoProductividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroContratoProductividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroContratoProductividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroContratoProductividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CancelaSus;
    private javax.swing.JCheckBox EliminaJuegos;
    private javax.swing.JCheckBox FiltrosCorreos;
    private javax.swing.JCheckBox SilenciaNot;
    private javax.swing.JCheckBox Silencioso;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables
}
